#!/bin/bash

##############
## HOME BIN ##
##############

## Path to the user binaries
if [[ "$(uname -s)" == Darwin ]]
then
    export HOME_BIN="$HOME/Library/bin"
else
    export HOME_BIN="$HOME/.local/bin"
fi

## Ensure HOME_BIN exists
[[ ! -d "$HOME_BIN" ]] && mkdir "$HOME_BIN"

## Add HOME_BIN to the PATH
export PATH="$HOME_BIN:$PATH"

##############
## HOMEBREW ##
##############

# Add the Homebrew PATH and Bash completion
if [[ "$(uname -s)" == Darwin && -d "$HOME/Library/Homebrew" ]]
then
    export PATH=$HOME/Library/Homebrew/bin:$PATH
    export PATH=$HOME/Library/Homebrew/sbin:$PATH
fi

#####################
## BASH COMPLETION ##
#####################

if [[ "$(uname -s)" == Darwin ]]
then
    if which brew &> /dev/null
    then
        #source $(brew --prefix)/etc/bash_completion
        #source $(brew --prefix)/Library/Contributions/brew_bash_completion.sh
        :
    fi
else
    [[ -z "$BASH_COMPLETION" && -f /etc/bash_completion ]] && export BASH_COMPLETION=/etc/bash_completion
    [[ -z "$BASH_COMPLETION_DIR" && -f /etc/bash_completion.d ]] && export BASH_COMPLETION_DIR=/etc/bash_completion.d
    [[ -z "$BASH_COMPLETION_COMPAT_DIR" && -f /etc/bash_completion.d ]] && export BASH_COMPLETION_COMPAT_DIR=/etc/bash_completion.d
fi

############
## EDITOR ##
############

if [[ "$(uname -s)" == Darwin ]]
then
    export EDITOR=nano
elif [[ -n "$DISPLAY" ]]
then
    export EDITOR=gedit
else
    export EDITOR=nano
fi

###########
## PAGER ##
###########

if which aless &> /dev/null
then
    export PAGER=aless
elif which most &> /dev/null
then
    export PAGER=most
fi

#################
## PYTHON EGGS ##
#################

# Mac OSX 10.7 Lion supports only Python 2.7
if [[ "$(uname -s)" == Darwin ]]
then
    export PYTHONPATH27=$HOME/Library/Python/2.7/site-packages
    export PATH=$PYTHONPATH27:$PATH
    export PYTHONPATH=$PYTHONPATH27:$PYTHONPATH

    # don't use the bloated easy_install
    alias easy_install='echo "!!! Deprecated"; false'

    # make pip use the default paths and install every egg into the user home
    function pip()
    {
	    pip=$(which pip)

    	if [[ $1 == install ]]
	    then
		    $pip $@ --install-option="--install-purelib=$PYTHONPATH27" --install-option="--install-platlib=$PYTHONPATH27" --install-option="--prefix=$PYTHONPATH27"
    	else
	    	$pip $@
    	fi
    }
    export -f pip
fi

#########
## GIT ##
#########

if which git &> /dev/null
then
    git config --global user.name "Stefano Varesi"
    # disabled: this creates a daemon and a warning is always raised when closing the window in Mac OSX
    #git config --global credential.helper cache
    git config --global color.ui true
    git config --global core.excludesfile /home/xstefanox/.gitignore.global
fi

#########
## WII ##
#########

[[ "$(uname -s)" == Darwin ]] && export PATH=/Volumes/WII/bin:$PATH || export PATH=/media/WII/bin:$PATH

##########
## MISC ##
##########

## Maximum allowed file size on a FAT32 filesystem
export FAT32_MAX_FILE_SIZE="$((2**32 - 1))"

## Size of a Nintendo WII ISO image
export WII_ISO_SIZE="4699979776"

## Localization
[[ -z "$LC_ALL" && -n "$LANG" ]] && export LC_ALL="$LANG"
[[ -z "$LANG" && -n "$LC_ALL" ]] && export LANG="$LC_ALL"

## Mac OSX
if [[ "$(uname -s)" == Darwin ]]
then

    # do not write useless trash to samba shares
    defaults write com.apple.desktopservices DSDontWriteNetworkStores true

    ## disable the warning when changing a file extension
    defaults write com.apple.finder FXEnableExtensionChangeWarning -bool false

## Linux
else

    ## Preferences requiring an active X11 session
    if [[ -n "$DISPLAY" ]]
    then
        if which gsettings &> /dev/null
        then
            gsettings set org.gnome.gedit.preferences.editor tabs-size 4
            gsettings set org.gnome.gedit.preferences.editor insert-spaces true
            gsettings set org.gnome.gedit.preferences.editor create-backup-copy false
            gsettings set org.gnome.gedit.preferences.editor display-line-numbers true
            gsettings set org.gnome.gedit.preferences.editor auto-indent true
        fi
    fi

fi
