#!/bin/bash

if which git &> /dev/null
then
    git config --global user.name "Stefano Varesi"
    git config --global credential.helper cache
    git config --global color.ui true
    git config --global core.excludesfile /home/xstefanox/.gitignore.global
fi

# preferences requiring an active X11 session
if [[ -n "$DISPLAY" ]]
then
    if which gsettings &> /dev/null
    then
        gsettings set org.gnome.gedit.preferences.editor tabs-size 4
        gsettings set org.gnome.gedit.preferences.editor insert-spaces true
        gsettings set org.gnome.gedit.preferences.editor create-backup-copy false
        gsettings set org.gnome.gedit.preferences.editor display-line-numbers true
        gsettings set org.gnome.gedit.preferences.editor auto-indent true
    fi
fi

